import СardLockIcon from "../../../assets/icons/СardLockIcon.svg";
import TestDataImageCard from "../../../assets/img/TestDataImageCard.png";

export const recommendedSelectData = {
  selectDefault: "Рекомендация",
  selectItem: [
    {
      id: "1",
      url: "#",
      text: "рекомендация 1",
    },
    {
      id: "2",
      url: "#",
      text: "рекомендация 2",
    },
  ],
};

export const filterSelectData = {
  selectDefault: "Фильтр",
  selectItem: [
    {
      id: "1",
      url: "#",
      text: "Фильтр 1",
    },
    {
      id: "2",
      url: "#",
      text: "Фильтр 2",
    },
  ],
};

export const catalogData = [
  {
    id: "1",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "2",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "3",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "4",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "5",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "6",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "7",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "8",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "9",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "10",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "11",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "12",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "13",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "14",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "15",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
];

const recentTransactionsDataSlide = [
  {
    id: "1",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "2",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "3",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "4",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "5",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "6",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
  {
    id: "7",
    lockIcon: СardLockIcon,
    lockTitle: "Разблокировано",
    image: TestDataImageCard,
    name: "Mace of Aeons",
    oldPrice: "32 545",
    discountProcent: "5",
    newPrice: "30 996",
  },
];

export const recentTransactionsData = [
  {
    id: "1",
    data: recentTransactionsDataSlide,
  },
  {
    id: "2",
    data: recentTransactionsDataSlide,
  },
];
